# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Continuous Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  preset-test:
    uses: ./.github/workflows/reusable-test.yml
    with:
      matrix_config: >
        {
          "gcc": [
            { "versions": ["15"],
              "tests": [
                { "cxxversions": ["c++26"],
                  "tests": [
                    { "stdlibs": ["libstdc++"],
                      "tests": ["Default", "TSan", "MaxSan", "Werror", "Dynamic"]
                    }
                  ]
                },
                { "cxxversions": ["c++23", "c++20", "c++17"],
                  "tests": [{"stdlibs": ["libstdc++"], "tests": ["Default"]}]
                }
              ]
            },
            { "versions": ["14", "13"],
              "tests": [
                { "cxxversions": ["c++26", "c++23", "c++20", "c++17"],
                  "tests": [{"stdlibs": ["libstdc++"], "tests": ["Default"]}]
                }
              ]
            },
            {
              "versions": ["12", "11"],
              "tests": [
                { "cxxversions": ["c++23", "c++20", "c++17"],
                  "tests": [{"stdlibs": ["libstdc++"], "tests": ["Default"]}]
                }
              ]
            }
          ],
          "clang": [
            { "versions": ["20"],
              "tests": [
                {"cxxversions": ["c++26"],
                  "tests": [
                    {
                      "stdlibs": ["libstdc++", "libc++"],
                      "tests": ["Default", "TSan", "MaxSan", "Werror", "Dynamic"]
                    }
                  ]
                },
                {
                  "cxxversions": ["c++23", "c++20", "c++17"],
                  "tests": [{"stdlibs": ["libstdc++", "libc++"], "tests": ["Default"]}]
                }
              ]
            },
            { "versions": ["19", "18", "17"],
              "tests": [
                { "cxxversions": ["c++26", "c++23", "c++20", "c++17"],
                  "tests": [{"stdlibs": ["libstdc++", "libc++"], "tests": ["Default"]}]
                }
              ]
            }
          ],
          "appleclang": [
            { "versions": ["latest"],
              "tests": [
                {
                  "cxxversions": ["c++26", "c++23", "c++20", "c++17"],
                  "tests": [{"stdlibs": ["libc++"], "tests": ["Default"]}]
                }
              ]
            }
          ],
          "msvc": [
            { "versions": ["latest"],
              "tests": [
                {
                  "cxxversions": ["c++latest"],
                  "tests": [{"stdlibs": ["stl"], "tests": ["Default", "MaxSan"]}]
                }
              ]
            }
          ]
        }
