# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: 'Beman preset test matrix'
on:
  workflow_call:
    inputs:
      matrix_config:
        description: 'todo'
        type: string
        required: true
jobs:
  preset_test_matrix:
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJSON(inputs.matrix_config) }}
    name: "${{ matrix.config.compiler }} ${{ matrix.config.version }} ${{ matrix.config.cxxversion }} ${{ toJSON(matrix.config.test) }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name:
        run: ./foo.sh ${{ matrix.config.test }}
