# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: 'Beman preset test matrix'
on:
  workflow_call:
    inputs:
      matrix_config:
        description: 'todo'
        type: string
        required: true
jobs:
  test_matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          matrix=$(echo '${{ inputs.matrix_config }}' | ./transform.py)
          echo "matrix=$(echo $matrix)" >> $GITHUB_OUTPUT
  test_matrix:
    needs: test_matrix_prep
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.test_matrix_prep.outputs.matrix) }}
    name: "${{ matrix.config.compiler }} ${{ matrix.config.version }} ${{ matrix.config.cxxversion }} ${{ matrix.config.stdlib }} ${{ matrix.config.test }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./foo.sh ${{ matrix.config.compiler }} ${{ matrix.config.version }} ${{ matrix.config.cxxversion }} ${{ matrix.config.stdlib }} ${{ matrix.config.test }}
